name: bicyc_go
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  web_socket_channel: ^2.2.0
  geolocator: ^10.0.0
  camera: ^0.11.1
  flutter_compass: ^0.8.0
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  